# Generated by Django 2.2 on 2019-04-11 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortener',
            options={'verbose_name': 'Encurtador', 'verbose_name_plural': 'Encurtadores'},
        ),
        migrations.AlterField(
            model_name='log',
            name='browser',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Navegador'),
        ),
        migrations.AlterField(
            model_name='log',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='log',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='log',
            name='shortener',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.Shortener', verbose_name='Encurtador'),
        ),
        migrations.AlterField(
            model_name='log',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='shortener',
            name='clicks',
            field=models.IntegerField(default=0, verbose_name='Cliques'),
        ),
        migrations.AlterField(
            model_name='shortener',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='shortener',
            name='shortened',
            field=models.CharField(blank=True, max_length=5, unique=True, verbose_name='Encurtado'),
        ),
    ]
